## Ajustando dataset para o kmeans

In [26]:
import os
import pandas as pd
import numpy as np
import re

### Lendo dataset

In [44]:
dataframe = pd.read_csv("DUCL0001C0001.csv")

In [45]:
del dataframe['Unnamed: 0']
dataframe = dataframe.head(10000)

In [46]:
dataframe

,X,Y,Z,intensity,return_number,number_of_returns,scan_direction_flag,edge_of_flight_line,classification,synthetic,key_point,withheld,scan_angle_rank,user_data,point_source_id,gps_time
0,83825705,967465751,7659,1,2,2,False,False,4,False,False,False,-25,0,2211,60788.611257
1,83825711,967465722,7633,1,2,2,False,False,4,False,False,False,-25,0,2211,60788.611267
2,83825704,967465777,7784,1,2,2,False,False,4,False,False,False,-25,0,2211,60788.611277
3,83825705,967465780,7824,2,1,1,False,False,4,False,False,False,-25,0,2211,60788.611287
4,83825708,967465767,7828,1,1,1,False,False,4,False,False,False,-26,0,2211,60788.611297
5,83825712,967465752,7857,2,2,2,False,False,4,False,False,False,-26,0,2211,60788.611317
6,83825715,967465741,7860,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611327
7,83825716,967465737,7880,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611337
8,83825716,967465748,7927,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611347
9,83825718,967465734,7921,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611357
10,83825723,967465723,7985,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611397
11,83825728,967465692,7939,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611407
12,83825713,967465802,8188,1,2,2,False,False,4,False,False,False,-26,0,2211,60788.611417
13,83825678,967466042,8709,5,1,1,False,False,4,False,False,False,-26,0,2211,60788.611427
14,83825680,967466032,8702,2,1,1,False,False,4,False,False,False,-26,0,2211,60788.611438
15,83825680,967466034,8720,1,1,1,False,False,4,False,False,False,-26,0,2211,60788.611447
16,83825680,967466040,8746,1,1,1,False,False,4,False,False,False,-26,0,2211,60788.611457
17,83825682,967466030,8736,1,1,1,False,False,4,False,False,False,-26,0,2211,60788.611467
18,83825682,967466033,8750,1,1,1,False,False,4,False,False,False,-26,0,2211,60788.611477
19,83825682,967466031,8754,4,1,1,False,False,4,False,False,False,-26,0,2211,60788.611487
20,83825684,967466021,8739,1,1,1,False,False,4,False,False,False,-26,0,2211,60788.611497
21,83825683,967466028,8758,4,1,1,False,False,4,False,False,False,-26,0,2211,60788.611507
22,83825684,967466024,8754,6,1,1,False,False,4,False,False,False,-26,0,2211,60788.611517
23,83825684,967466027,8762,4,1,1,False,False,4,False,False,False,-26,0,2211,60788.611527
24,83825683,967466032,8780,1,1,1,False,True,4,False,False,False,-26,0,2211,60788.611537
25,83825684,967466024,8760,4,1,1,True,False,4,False,False,False,-26,0,2211,60788.611547
26,83825683,967466029,8769,3,1,1,True,False,4,False,False,False,-26,0,2211,60788.611557
27,83825683,967466029,8767,1,1,1,True,False,4,False,False,False,-26,0,2211,60788.611567
28,83825683,967466029,8762,4,1,1,True,False,4,False,False,False,-26,0,2211,60788.611577
29,83825683,967466031,8762,2,1,1,True,False,4,False,False,False,-26,0,2211,60788.611587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,83826926,967469329,9537,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362233
9971,83826918,967469369,9549,4,1,1,True,False,4,False,False,False,-23,0,2211,60789.362244
9972,83826911,967469402,9547,4,1,1,True,False,4,False,False,False,-23,0,2211,60789.362253
9973,83826900,967469475,9638,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362263
9974,83826902,967469431,9454,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362273
9975,83826896,967469456,9432,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362283
9976,83826891,967469478,9402,6,1,1,True,False,4,False,False,False,-23,0,2211,60789.362293
9977,83826854,967469750,9960,1,1,3,True,False,4,False,False,False,-23,0,2211,60789.362303
9978,83826893,967469434,9217,1,2,3,True,False,4,False,False,False,-23,0,2211,60789.362303
9979,83826920,967469221,8714,1,3,3,True,False,4,False,False,False,-23,0,2211,60789.362303
9980,83826847,967469782,9955,2,1,2,True,False,4,False,False,False,-23,0,2211,60789.362314
9981,83826891,967469427,9117,1,2,2,True,False,4,False,False,False,-23,0,2211,60789.362314
9982,83826841,967469813,9948,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362324
9983,83826830,967469878,10019,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362334
9984,83826823,967469909,10010,5,1,1,True,False,4,False,False,False,-23,0,2211,60789.362344
9985,83826817,967469937,9995,1,1,1,True,False,4,False,False,False,-23,0,2211,60789.362354
9986,83826814,967469935,9909,5,1,2,True,False,4,False,False,False,-23,0,2211,60789.362364
9987,83826853,967469618,9156,1,2,2,True,False,4,False,False,False,-23,0,2211,60789.362364
9988,83826778,967470205,10471,1,1,2,True,False,5,False,False,False,-23,0,2211,60789.362373
9989,83826845,967469662,9180,1,2,2,True,False,4,False,False,False,-23,0,2211,60789.362373
9990,83826772,967470234,10460,1,1,3,True,False,5,False,False,False,-23,0,2211,60789.362384
9991,83826807,967469948,9779,1,2,3,True,False,4,False,False,False,-23,0,2211,60789.362384
9992,83826887,967469296,8225,1,3,3,True,False,4,False,False,False,-23,0,2211,60789.362384
9993,83826765,967470266,10456,1,1,3,True,False,5,False,False,False,-23,0,2211,60789.362394
9994,83826797,967470005,9834,2,2,3,True,False,4,False,False,False,-23,0,2211,60789.362394
9995,83826839,967469666,9023,2,3,3,True,False,4,False,False,False,-23,0,2211,60789.362394
9996,83826758,967470296,10445,1,1,2,True,False,5,False,False,False,-23,0,2211,60789.362403
9997,83826787,967470059,9880,1,2,2,True,False,4,False,False,False,-23,0,2211,60789.362403
9998,83826783,967470074,9832,3,1,3,True,False,4,False,False,False,-23,0,2211,60789.362413
9999,83826815,967469811,9204,1,2,3,True,False,4,False,False,False,-23,0,2211,60789.362413

In [47]:
dataframe=dataframe.apply(lambda x: x.replace(True,int(1)))
dataframe=dataframe.apply(lambda x: x.replace(False,int(0)))