# Objetivo : 
### mover a coluna 'classification' para ser a ultima coluna e salvar como '0_DataFrame.csv'

In [8]:
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import style
%matplotlib inline

In [9]:
dataframe = pd.read_csv("DUCL0001C0001.csv")
del dataframe['Unnamed: 0']

In [10]:
data = dataframe
nome_colunas =list(data.columns)

dt_classification = pd.DataFrame(np.array(data['classification']),columns=['classification'])
data.drop(columns=['classification'],axis=1,inplace=True)

In [11]:
dataframe = pd.concat([data,dt_classification], axis=1, ignore_index=False)

In [12]:
dataframe=dataframe[dataframe.classification!=1]

In [13]:
dataframe=dataframe[dataframe.classification!=7]

In [14]:
dataframe.drop(['key_point','withheld','synthetic','gps_time','user_data','X','point_source_id'],axis=1,inplace=True)
dataframe

,Y,Z,intensity,return_number,number_of_returns,scan_direction_flag,edge_of_flight_line,scan_angle_rank,classification
0,967465751,7659,1,2,2,False,False,-25,4
1,967465722,7633,1,2,2,False,False,-25,4
2,967465777,7784,1,2,2,False,False,-25,4
3,967465780,7824,2,1,1,False,False,-25,4
4,967465767,7828,1,1,1,False,False,-26,4
5,967465752,7857,2,2,2,False,False,-26,4
6,967465741,7860,1,2,2,False,False,-26,4
7,967465737,7880,1,2,2,False,False,-26,4
8,967465748,7927,1,2,2,False,False,-26,4
9,967465734,7921,1,2,2,False,False,-26,4
10,967465723,7985,1,2,2,False,False,-26,4
11,967465692,7939,1,2,2,False,False,-26,4
12,967465802,8188,1,2,2,False,False,-26,4
13,967466042,8709,5,1,1,False,False,-26,4
14,967466032,8702,2,1,1,False,False,-26,4
15,967466034,8720,1,1,1,False,False,-26,4
16,967466040,8746,1,1,1,False,False,-26,4
17,967466030,8736,1,1,1,False,False,-26,4
18,967466033,8750,1,1,1,False,False,-26,4
19,967466031,8754,4,1,1,False,False,-26,4
20,967466021,8739,1,1,1,False,False,-26,4
21,967466028,8758,4,1,1,False,False,-26,4
22,967466024,8754,6,1,1,False,False,-26,4
23,967466027,8762,4,1,1,False,False,-26,4
24,967466032,8780,1,1,1,False,True,-26,4
25,967466024,8760,4,1,1,True,False,-26,4
26,967466029,8769,3,1,1,True,False,-26,4
27,967466029,8767,1,1,1,True,False,-26,4
28,967466029,8762,4,1,1,True,False,-26,4
29,967466031,8762,2,1,1,True,False,-26,4
...,...,...,...,...,...,...,...,...,...
11827658,967413741,7179,1,2,2,True,False,-24,4
11827659,967413382,7914,1,1,2,True,False,-24,4
11827660,967413725,7132,1,2,2,True,False,-24,4
11827661,967413354,7895,1,1,3,True,False,-24,4
11827662,967413761,6965,1,2,3,True,False,-24,4
11827663,967414077,6246,1,3,3,True,False,-24,3
11827664,967413345,7830,1,1,2,True,False,-24,4
11827665,967413588,7275,1,2,2,True,False,-24,4
11827666,967413491,7329,4,1,2,True,False,-24,4
11827667,967413830,6552,2,2,2,True,False,-24,3
11827668,967413438,7366,6,1,1,True,False,-24,4
11827669,967413401,7367,2,1,1,True,False,-24,4
11827670,967413368,7357,5,1,1,True,False,-24,4
11827671,967413301,7425,1,1,1,True,False,-24,4
11827672,967413255,7446,3,1,2,True,False,-24,4
11827673,967413398,7115,1,2,2,True,False,-24,4
11827674,967413224,7431,1,1,1,True,False,-24,4
11827675,967412776,6375,1,2,2,True,False,-23,3
11827676,967412478,6006,1,3,3,True,False,-23,2
11827677,967412184,6265,1,3,3,True,False,-22,3
11827678,967414180,6165,1,2,2,False,False,-24,2
11827679,967414211,6181,3,1,1,False,False,-24,2
11827680,967414848,6209,1,2,2,False,False,-24,2
11827681,967415800,7864,1,2,2,False,False,-26,4
11827682,967416028,7848,2,2,2,False,False,-26,4
11827683,967416026,7855,1,2,2,True,False,-26,4
11827684,967416029,7825,1,2,2,True,False,-26,4
11827685,967415873,7425,1,3,3,True,False,-26,4
11827686,967415686,6806,1,2,2,True,False,-25,3
11827687,967414773,6200,1,3,3,True,False,-24,2

In [15]:
dataframe=dataframe.apply(lambda x: x.replace(True,int(1)))

In [16]:
dataframe=dataframe.apply(lambda x: x.replace(False,int(0)))

In [ ]:
#gerar o arquivo com a modificação
dataframe.to_csv('0_DataFrame.csv')